coverage:
    range: 50..100
    round: nearest
    precision: 1
    status:
        project:
            default:
                target: 80
                threshold: 1
        patch:
            default:
                target: 90
ignore:
   - polyply/tests
comment: off
